
basic: basic.cu
	nvcc -diag-suppress 550 -O2 -lm basic.cu -o basic

sample: sample.cu
	nvcc -diag-suppress 550 -O2 -lm sample.cu -o sample

sequential: sequential.c
	gcc -O2 -lm sequential.c -o sequential

